Make sure data is of type 'bytes'
Py3 interprets `data` as 'bytes' and Py2 as 'str', because of which it throws
the traceback:

  File "build/bdist.linux-x86_64/egg/conda_verify/cli.py", line 40, in cli
  File "build/bdist.linux-x86_64/egg/conda_verify/verify.py", line 30, in verify_package
  File "build/bdist.linux-x86_64/egg/conda_verify/checks.py", line 310, in check_windows_arch
  File "build/bdist.linux-x86_64/egg/conda_verify/utilities.py", line 120, in get_object_type
TypeError: cannot concatenate 'str' and 'NoneType' objects

This patch makes sure that the input for computing the DLL_TYPE is indeed an
integer, by changing forcing data to always be of type bytes.